#! /bin/bash
cd ../asserts

echo "Copying files"
cp css/rca-cricket.css ../plugin/cricket-api/views/
cp -r css/themes  ../plugin/cricket-api/views/
cp js/rca-cricket-angular.js ../plugin/cricket-api/views/
cp views/*	../plugin/cricket-api/views/

echo "Creating Zip file"
cd ../plugin/
zip -r cricket-api.zip cricket-api
mv cricket-api.zip ../release/