#! /bin/bash
cd ../asserts

echo "Copying files"
cp css/rca-cricket.css ../plugin/cricket-api/views/
cp css/themes/*  ../plugin/cricket-api/views/themes/
cp js/rca-cricket-angular.js ../plugin/cricket-api/views/

echo "Creating Zip file"
cd ../plugin/
zip -r cricket-api.zip cricket-api
mv cricket-api.zip ../release/